"""init

Revision ID: e1ad25e6055a
Revises: 
Create Date: 2025-09-05 17:59:24.838401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1ad25e6055a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_fee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('int_proxy_min', sa.Float(), nullable=True),
    sa.Column('int_proxy_max', sa.Float(), nullable=True),
    sa.Column('int_fee', sa.Float(), nullable=True),
    sa.Column('proxy_fee', sa.Float(), nullable=True),
    sa.Column('live_bid_min', sa.Float(), nullable=True),
    sa.Column('live_bid_max', sa.Float(), nullable=True),
    sa.Column('live_bid_fee', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_int_proxy_range', 'additional_fee', ['int_proxy_min', 'int_proxy_max'], unique=False)
    op.create_index('idx_live_bid_range', 'additional_fee', ['live_bid_min', 'live_bid_max'], unique=False)
    op.create_index(op.f('ix_additional_fee_id'), 'additional_fee', ['id'], unique=False)
    op.create_table('additional_special_fee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('auction', sa.Enum('COPART', 'IAAI', name='auctionenum'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_additional_special_fee_id'), 'additional_special_fee', ['id'], unique=False)
    op.create_table('destination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_destination_id'), 'destination', ['id'], unique=False)
    op.create_table('exchange_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_rate_id'), 'exchange_rate', ['id'], unique=False)
    op.create_table('fee_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auction', sa.Enum('COPART', 'IAAI', name='auctionenum'), nullable=False),
    sa.Column('fee_type', sa.Enum('CLEAN_TITLE_FEE', 'NON_CLEAN_TITLE_FEE', 'CRASHED_TOYS_FEE', 'LESS_FEE', name='feetypeenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_type_id'), 'fee_type', ['id'], unique=False)
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_location_id'), 'location', ['id'], unique=False)
    op.create_table('terminal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_terminal_id'), 'terminal', ['id'], unique=False)
    op.create_table('vehicle_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auction', sa.Enum('COPART', 'IAAI', name='auctionenum'), nullable=True),
    sa.Column('vehicle_type', sa.Enum('CAR', 'MOTO', name='vehicletypeenum'), nullable=True),
    sa.Column('specific_type', sa.Enum('DEALER', name='specificauctionenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_type_id'), 'vehicle_type', ['id'], unique=False)
    op.create_table('delivery_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('terminal_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminal.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_price_id'), 'delivery_price', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_price_location_id'), 'delivery_price', ['location_id'], unique=False)
    op.create_index(op.f('ix_delivery_price_terminal_id'), 'delivery_price', ['terminal_id'], unique=False)
    op.create_index(op.f('ix_delivery_price_vehicle_type_id'), 'delivery_price', ['vehicle_type_id'], unique=False)
    op.create_table('fee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_price_min', sa.Float(), nullable=False),
    sa.Column('car_price_max', sa.Float(), nullable=False),
    sa.Column('car_price_fee', sa.Float(), nullable=False),
    sa.Column('fee_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fee_type_id'], ['fee_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fee_type_price_range', 'fee', ['fee_type_id', 'car_price_min', 'car_price_max'], unique=False)
    op.create_index(op.f('ix_fee_id'), 'fee', ['id'], unique=False)
    op.create_table('shipping_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('terminal_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminal.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_price_destination_id'), 'shipping_price', ['destination_id'], unique=False)
    op.create_index(op.f('ix_shipping_price_id'), 'shipping_price', ['id'], unique=False)
    op.create_index(op.f('ix_shipping_price_terminal_id'), 'shipping_price', ['terminal_id'], unique=False)
    op.create_index(op.f('ix_shipping_price_vehicle_type_id'), 'shipping_price', ['vehicle_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipping_price_vehicle_type_id'), table_name='shipping_price')
    op.drop_index(op.f('ix_shipping_price_terminal_id'), table_name='shipping_price')
    op.drop_index(op.f('ix_shipping_price_id'), table_name='shipping_price')
    op.drop_index(op.f('ix_shipping_price_destination_id'), table_name='shipping_price')
    op.drop_table('shipping_price')
    op.drop_index(op.f('ix_fee_id'), table_name='fee')
    op.drop_index('idx_fee_type_price_range', table_name='fee')
    op.drop_table('fee')
    op.drop_index(op.f('ix_delivery_price_vehicle_type_id'), table_name='delivery_price')
    op.drop_index(op.f('ix_delivery_price_terminal_id'), table_name='delivery_price')
    op.drop_index(op.f('ix_delivery_price_location_id'), table_name='delivery_price')
    op.drop_index(op.f('ix_delivery_price_id'), table_name='delivery_price')
    op.drop_table('delivery_price')
    op.drop_index(op.f('ix_vehicle_type_id'), table_name='vehicle_type')
    op.drop_table('vehicle_type')
    op.drop_index(op.f('ix_terminal_id'), table_name='terminal')
    op.drop_table('terminal')
    op.drop_index(op.f('ix_location_id'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_fee_type_id'), table_name='fee_type')
    op.drop_table('fee_type')
    op.drop_index(op.f('ix_exchange_rate_id'), table_name='exchange_rate')
    op.drop_table('exchange_rate')
    op.drop_index(op.f('ix_destination_id'), table_name='destination')
    op.drop_table('destination')
    op.drop_index(op.f('ix_additional_special_fee_id'), table_name='additional_special_fee')
    op.drop_table('additional_special_fee')
    op.drop_index(op.f('ix_additional_fee_id'), table_name='additional_fee')
    op.drop_index('idx_live_bid_range', table_name='additional_fee')
    op.drop_index('idx_int_proxy_range', table_name='additional_fee')
    op.drop_table('additional_fee')
    # ### end Alembic commands ###
