name: Fast Multi-arch Pipeline
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Cache poetry dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run tests
        run: |
          echo "Running tests..."
          poetry run pytest || ([ $? -eq 5 ] && echo "⚠️ No tests found - continuing anyway" || exit $?)

  build:
    needs: test
    if: github.event_name == 'push'
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            platform: linux/amd64
            cache-tag: amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
            cache-tag: arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: ${{ matrix.platform }}
          outputs: type=image,name=${{ secrets.DOCKERHUB_USERNAME }}/vinaslt_calculator_service,push-by-digest=true,name-canonical=true,push=true
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/vinaslt_calculator_service:buildcache-${{ matrix.cache-tag }}
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/vinaslt_calculator_service:buildcache-${{ matrix.cache-tag }},mode=max

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.cache-tag }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/vinaslt_calculator_service:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/vinaslt_calculator_service:${{ github.sha }} \
            $(printf '${{ secrets.DOCKERHUB_USERNAME }}/vinaslt_calculator_service@sha256:%s ' *)

  deploy:
    needs: merge
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -x
            echo "🔁 Pulling latest Docker image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/vinaslt_calculator_service:latest
            
            echo "📦 Composing up..."
            cd /srv/vinaslt/deploy_conf
            docker compose up -d --build
            
            echo "✅ Deployment complete!"